apiVersion: apps/v1
kind: Deployment
metadata:
  name: apln-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apln-operator
  template:
    metadata:
      labels:
        name: apln-operator
    spec:
      serviceAccountName: apln-operator
      containers:
        - name: apln-operator
          # Replace this with the built image name
          image: lubowsky/apln-operator:latest
          command:
          - apln-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apln-operator"
