apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: aplns.apln.example.com
spec:
  group: apln.example.com
  names:
    kind: Apln
    listKind: AplnList
    plural: aplns
    singular: apln
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Apln is the Schema for the aplns API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AplnSpec defines the desired state of Apln
          type: object
        status:
          description: AplnStatus defines the observed state of Apln
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
